import type { Metadata } from 'next';
// import { AntdRegistry } from "@ant-design/nextjs-registry";
import { Inter } from 'next/font/google';
import './globals.css';
import { languages } from '@/i18n';
const inter = Inter({ subsets: ['latin'] });

import { dir } from 'i18next';

export async function generateStaticParams() {
	return languages.map((lng) => ({ lng }));
}

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
};

export default function RootLayout({
	children,
	params: { lng }
}: Readonly<{
	children: React.ReactNode;
	params: { lng: string };
}>) {
	console.log(lng);

	return (
		<html lang={lng} dir={dir(lng)}>
			<body className="min-h-screen">
				<>{children}</>
			</body>
		</html>
	);
}
